### ISSUE TITLE
Cocoapods collisions

### ISSUE THREAD

**Issue by dehesa** [pauljohanneskraft/CodableCSV#5]
Hi @pauljohanneskraft,

I am the repo owner from another CSV library, which coincidentally is also called CodableCSV. You can find it [here](https://github.com/dehesa/CodableCSV).

It has been brought to my attention ([here](https://github.com/dehesa/CodableCSV/issues/23), [here](https://github.com/dehesa/CodableCSV/issues/5), and [here](https://github.com/dehesa/CodableCSV/pull/4)) that users are getting confused when trying to install the library through Cocoapods. I am not a Cocoapods user and the podspec was added by a contributor some time ago. I tried to solve the problem, but it seems you have already registered the _CodableCSV_ name on the pods trunk. I wanted to reach out to you and kindly ask whether you would mind releasing the name to me.

I am aware that I don't deserve the name domain more than you (funnily we started the library almost at the same time). If you feel very attach to it, maybe you can give me a suggestion how to resolve this problem. As I stated before, I don't have experience with Cocoapods.

Regards,
Marcos

**Comment by pauljohanneskraft** [comment]
Hey - sorry that it took me so long to respond. I'm fine with you getting the name - what do I need to do for that?

**Comment by dehesa** [comment]
Hi @pauljohanneskraft,

No worries, thank you for answering. To be honest, I have no idea. I was hoping you knew. But now that I know you don't know 😅 I will try to look for the answer.

Regards

**Comment by pauljohanneskraft** [comment]
Alright, so I just deleted all the pushed versions of CodableCSV using `pod trunk delete`, so it should be open again.

I hope, nobody grabs it in the mean time 😊

**Comment by dehesa** [comment]
That was great help Paul, thank you. I did try to push after registering (`pod trunk push CodableCSV.podspec`); however they still tell me you are the owner.

```
You (san.dehesa@gmail.com) are not allowed to push new versions for this pod. The owners of this pod are pauljohanneskraft@icloud.com.
```

I was looking at their command-line help `pod trunk --help` and there were some interesting information.
- `pod trunk delete` only deletes a version of a pod (not the pod itself).
- `pod trunk add-owner` adds an owner to the pod.
- `pod trunk remove-owner` removes an owner from a pod.

Could you please add me as an owner to the pod? (don't just yet delete yourself, in case there are problems). Then I will check access and delete you later.

**Comment by pauljohanneskraft** [comment]
Alright - I added you as an owner. 

As a sidenote: To actually change anything about the pod required me to push a new version. So, I pushed a new version, then added you as the owner, then deleted the version again. There should now no longer be any versions and you should be able to push versions to Cocoapods. You can now simply remove me as an owner of the Cocoapod.

**Comment by dehesa** [comment]
Hey Paul,

I have managed to push a new version and remove you from ownership successfully. Thank you for hearing me out and be so ready to perform extra work. I appreciate it!

Regards
